name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Chỉ chạy khi có thay đổi trên branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Build dự án
      - name: Build project
        run: npm run build

      # Bước 5: Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Thư mục chứa file tĩnh
