name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Chỉ chạy khi có thay đổi trên branch main
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set NODE_ENV
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      - name: Install TypeScript and ESLint
        run: npm install --save-dev eslint typescript @types/react @types/node

      # Bước 4: Build và Export Next.js project
      - name: Build project
        run: npm run build

      # Bước 5: Deploy lên nhánh gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Thư mục chứa các file tĩnh
          publish_branch: gh-pages # Nhánh mà bạn muốn deploy
